Fix: IPv6 forwarding caused issue on some development servers.
aleph-im/aleph-vm pull request #357
Opened 2023-07-04 09:34 UTC by hoh

Solution: Add a setting to disable IPv6 forwarding. Forwarding is enabled by default.

2023-07-04 12:18 UTC, odesenfans requested changes

2023-07-04 12:18 UTC, odesenfans commented on vm_supervisor/network/hostnetwork.py
> +        if not settings.IPV6_FORWARDING_ENABLED:
Could you pass that setting to the constructor instead?

2023-07-06 08:31 UTC, hoh commented on vm_supervisor/network/hostnetwork.py
> +        ipv6_forwarding_enabled: bool = True,
To make the use of the NDP proxy explicit, since it is starting a daemon I believe it is important that the caller always knows about that.

2023-07-06 08:35 UTC, odesenfans approved these changes

2023-07-06 08:36 UTC, merged