Fix: AttributeError: 'MicroVM' object has no attribute 'send_shutdown_message'
aleph-im/aleph-vm pull request #653
Opened 2024-07-04 13:28 UTC by hoh

Error reported on https://github.com/aleph-im/aleph-vm/issues/652

2024-07-04 13:36 UTC, nesitor approved these changes

2024-07-04 14:03 UTC, olethanh requested changes

2024-07-04 14:03 UTC, olethanh commented on src/aleph/vm/hypervisors/qemu/qemuvm.py
> +        """Stop the VM, cleanup network interface and remove data directory."""
The docstring is wrong
it's not actually doing any of that except stopping the vm.

Even on microvm it's not cleaning up the interface

2024-07-05 10:00 UTC, olethanh commented on src/aleph/vm/hypervisors/qemu/qemuvm.py
> +        """Stop the VM, cleanup network interface and remove data directory."""
```suggestion
        """Stop the VM."""
```

2024-07-05 13:36 UTC, olethanh approved these changes

2024-07-05 13:37 UTC, merged